### ISSUE TITLE
v1.0.3 breaks NextJS projects (and maybe others?)

### ISSUE THREAD

**Issue by dotansimha** [suren-atoyan/state-local#3]
I have this dependency because of [monaco-react](https://github.com/suren-atoyan/monaco-react/blob/master/package.json#L88), and it seems like the latest version (1.0.3) is not compatible with the default setup of NextJS. Tried both TS and JS setups, it just seems like the `main` of the library points to a source code file that isn't supported by all environments.  I assume it might be related to the optional chaining sign? 

The actual error i'm getting :

```
error - ../node_modules/state-local/src/state/index.js 48:41
Module parse failed: Unexpected token (48:41)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     ? handler(state.current)
|     : Object.keys(changes)
>         .forEach(field => handler[field]?.(state.current[field]));
| 
|   return changes;
```

Thanks @suren-atoyan

**Comment by suren-atoyan** [comment]
Hello @dotansimha 

I just reverted the last changes, please check the v1.0.4

**Comment by dotansimha** [comment]
1.0.4 works. Thanks!
